// app/layout.tsx
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Vazirmatn } from 'next/font/google'
import ThemeProviderWrapper from "@/components/providers/theme-provider";


const vazirmatn = Vazirmatn({ 
  subsets: ["arabic"],
  display: 'swap',
})

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html dir="rtl" lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${vazirmatn.className} antialiased`}>
        <ThemeProviderWrapper attribute="class" defaultTheme="system" enableSystem>
          {children}
        </ThemeProviderWrapper>
      </body>
    </html>
  );
}
